[package]
name = "db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "2.0.4", features = ["mysql", "r2d2", "chrono"] }
dotenv = "0.15.0"
r2d2 = "0.8"
lazy_static = "1.4"